version: '3'
services:
  api:
    container_name: api
    environment:
      EMAIL_SMTP: ${EMAIL_SMTP}
      EMAIL_HOSTNAME: ${EMAIL_HOSTNAME}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      AUTH_GUARDIAN: ${AUTH_GUARDIAN}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_DEV: ${DB_DATABASE_DEV}
      DB_DATABASE_TEST: ${DB_DATABASE_TEST}
    build: .
    command: /bin/bash docker_start.sh
    volumes:
      - .:/bank_stone
    ports:
      - "4000:4000"
    links:
      - database
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - "./volumes/datadir:/var/lib/postgres"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_DEV}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "5432:5432"