version: '3'
services:
  api:
    container_name: bank_stone
    build: .
    command: /bin/bash docker_start.sh
    volumes:
      - .:/bank_stone
    ports:
      - "4000:4000"
    links:
      - database
  database:
    container_name: database
    image: postgres
    restart: always
    volumes:
      - "./volumes/datadir:/var/lib/postgres"
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bank_stone_dev
      POSTGRES_USER: root
    ports:
      - "5432:5432z"